select * from LOGINCREDENTIALS


CREATE DATABASE InstaDB

CREATE TABLE LOGINCREDENTIALS (UserName  varchar(27)UNIQUE NOT NULL ,Password  varchar(27) NOT NULL,
MobileNumber bigint,FullName varchar(27))

DROP TABLE LOGINCREDENTIALS
SELECT * FROM LOGINCREDENTIALS


create procedure CheckCrentials
AS BEGIN
select LOGINCREDENTIALS.UserName,LOGINCREDENTIALS.Password from LOGINCREDENTIALS
END


create procedure InsertData
(@USERNAME VARCHAR(27),@PASSWORD VARCHAR(27),@MOBILENUMBER BIGINT,@FULLNAME VARCHAR(27))
AS BEGIN
INSERT INTO LOGINCREDENTIALS(USERNAME,PASSWORD,MOBILENUMBER,FULLNAME)
VALUES(@USERNAME,@PASSWORD,@MOBILENUMBER,@FULLNAME)
END








